task: classification
num_classes: 2
net:
  type: PointCNN
  hidden_dim: 512
  out_dim: 512
loss:
  bce_loss:
    weight: 1.0
    learn_weight: false
  mse_loss:
    weight: 0.0
    learn_weight: false
optim:
  lr: 0.0003
  lr_min: 1.0e-06
  lr_scheduler: reduceonplateau
  warmup_epochs: 0
  lr_patience: 10
  lr_reduce_factor: 0.9
  lr_adjust: false
  lr_adjust_rule: ''
  weight_decay: 0
  weight_decay_end: 1.0
  clip_grad: 1.0
data:
  img_height: 480
  img_width: 480
  n_channels: 1
  aug_photo: 0.0
  aug_geome: 0.5
  data_dir: ../data/near_field
  dsets:
  - Grating
  - Laseroptik
  - Thales
  train_datasets:
  - Grating_A6
  - Grating_SON1
  - LASEROPTIK
  - LASEROPTIK_SON1
  - LASEROPTIK_10000
  - THALES_SESO_10000
  test_datasets:
  - THALES_SESO_A
  val_split: 0.2
  prefetch: 1
train:
  epochs: 500
  batch_size: 32
  num_workers: 1
  gpu: 0
  ddp: false
  dist_run: false
  resume_training: false
  single_batch: false
  debug: false
  early_stop_metric: val/acc
  early_stop_patience: 5
  eval_interval: 10
  log_interval: 100
  n_images: 20
  eval_metric: val/acc
  train_skip_frames: 1
  test_skip_frames: 1
  reset_head_steps: null
  network_in: null
exp:
  name: exp5
  session: 2
  log_dir: ../logs
  ckpt_dir: null
  summary_dir: null
  seed: 3061994
